apiVersion: s3.aws.crossplane.io/v1beta1
kind: Bucket
metadata:
  name: mansong-crossplane-test
spec:
  providerConfigRef:
    name: aws-provider
  forProvider:
    locationConstraint: 'us-east-2'
    acl: private